CC:=gcc

fopen_test:fopen_test.c
#gcc -o fopen_test fopen_test.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@


fclose:fclose.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputc:fputc.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fprintf:fprintf.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@


fgetc:fgetc.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fscanf:fscanf.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

stdin:stdin.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@


unistd:unistd.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@


all:all.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@
	